version: '3'

services:

   web1:
     container_name: ${CONTAINER_NAME}
     image: lasa/brunssille
     restart: unless-stopped
     volumes:
       - ${FILES_CORE}:/var/www/html
     environment:
       VIRTUAL_HOST: ${DOMAINS}
       LETSENCRYPT_HOST: ${DOMAINS}
       LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL} 

networks:
    default:
       external:
         name: ${NETWORK}
